---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-kustomize-consul
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./overlays/flux-kustomize-consul
  prune: true
  sourceRef:
    kind: GitRepository
    name: sandbox-flux
  targetNamespace: default

