---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-consul-kustomize-do
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./overlays/kube-consul-kustomize-do
  prune: true
  sourceRef:
    kind: GitRepository
    name: sandbox-flux
  targetNamespace: default

